### ISSUE TITLE
Can't destroy item b-1174

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#91] opened 2020-08-02 16:58 UTC
This caused a 500 error. Investigate and fix 😄

**Comment by avinashupadhya99** [comment] 2020-11-01 18:40
Any steps to reproduce or the log files when this occurs would be helpful in fixing this.

**Comment by rkim00** [comment] 2020-11-01 22:11
Hi @avinashupadhya99 . I'm not sure if the bug is in Production or Staging... I think Staging has a duplicate of the Production database so you might be able to debug there. In Staging, you can reproduce by:

1) Go to https://circulate-staging.herokuapp.com/admin/items/226/edit

2) Go the bottom of the page, click on the caret next to "Destroy Item?" at the bottom to reveal the "Destroy Item" button

3) Click on "Destroy Item" and confirm "OK."

4) Notice error messaging that results.

Let me know if that's helpful or not. Thanks so much for your help!

**Comment by avinashupadhya99** [comment] 2020-11-02 07:44
I was able to check that in the staging. I want to be able to reproduce this on my local so I can get the logs. I'll try to see if I find any differences in this item and other items. I guess this is the only way to reproduce it on my local.

**Closed** 2020-11-15 15:30 UTC
Labels: bug, needs-details, production, ruby
