### ISSUE TITLE
Add text to member Loan page to clarify the policy that tools on hold by another member can't be renewed.

### ISSUE THREAD

**Issue by CTLvivek** [rubyforgood/circulate#682] opened 2021-09-18 03:20 UTC
When a tool is on hold by another member, the button to "Request Renewal" is just gone, but there is no explanation of why the button isn't there.  

As a librarian, we get questions about renewals and issues with renewals on occasion. A small change might reduce the confusion. Maybe adding text like the following in the place where the renewal button would be. 

"This item can't be renewed because it is on hold by another member."

Or policy clarification could be added to the information sidebar.

**Comment by jim** [comment] 2021-09-21 15:47
Duplicate of #555

**Closed by jim** 2021-09-21 15:47 UTC
Labels: Type: 💅 UX / Usability, Priority: High
